language: c
addons:
   apt:
      packages:
      - cmake
      - autoconf
      - automake
      - libtool
      - valgrind
cache:
   directories:
      - ./ulfm-install
setup_ulfm:
   - echo "Configuring ULFM"
   - if [ -f ulfm-install/lib/libmpi.so ]; then
       echo "libmpich.so found -- nothing to build.";
       cd ulfm-install;
     else
       ROOT=`pwd`;
       echo "Downloading ULFM from repo";
       wget https://bitbucket.org/icldistcomp/ulfm2/get/ulfm2.0rc.tar.bz2;
       tar -xjf ulfm2.0rc.tar.bz2;
       mv icldist* ulfm-src/;
       echo " - Configuring and building ULFM.";
       cd ulfm-src;
       echo " - Running autogen.pl";
       ./autogen.pl >./ulfm_build_output.txt 2>&1;
       echo " - Running configure";
       ./configure --prefix=$ROOT/ulfm-install >>./ulfm_build_output.txt 2>&1;
       echo " - Running make";
       make -j4 >>./ulfm_build_output.txt 2>&1;
       echo " - Running make install";
       make install >>./ulfm_build_output.txt 2>&1;
       echo " - Finished installing ULFM";
       cd ../ulfm-install/;
     fi
    
   #Expect that any changes to the above still puts me in the install's home dir
   - export MPI_HOME=`pwd`
   - export PATH=$MPI_HOME/bin/:$PATH
   - export LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH
   - export DYLD_LIBRARY_PATH=$MPI_HOME/lib:$DYLD_LIBRARY_PATH
   - export MANPATH=$MPI_HOME/share/man:$MANPATH
    
   - export MPICC="`which mpicc`"
   - export MPICXX="`which mpic++`"

   - export OMPI_MCA_rmaps_base_oversubscribe "1"
    
   #Assuming the install's home dir is one above current.
   - cd ../
install:
   - mkdir build && cd build
   - cmake ../ -DBUILD_TESTING=ON && make -j4 VERBOSE=1
   - cd ../ #Always end back at the root directory
script:
   - cd build
   - make test
   - cd ../ #Always end back at the root directory.
after_failure:
   - echo "Failure occured, printing run logs:"
   - pwd
   - cat build/Testing/Temporary/LastTest.log
   - echo "Printing ULFM build log tail. If no output, ULFM was built before this test run"
   - tail -n100 .travis_helpers/build_output.txt
